In [1]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [3]:
train_images.shape

len(train_labels) 

train_labels


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [4]:
test_images.shape

len(test_labels) 

test_labels


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [5]:
from tensorflow import keras 
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [6]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [7]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255 
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

In [8]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
469/469 [==============================] - 6s 10ms/step - loss: 0.2582 - accuracy: 0.9248
Epoch 2/5
469/469 [==============================] - 5s 11ms/step - loss: 0.1051 - accuracy: 0.9689
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0685 - accuracy: 0.9797
Epoch 4/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0500 - accuracy: 0.9846
Epoch 5/5
469/469 [==============================] - 5s 11ms/step - loss: 0.0370 - accuracy: 0.9888


In [9]:
>>> test_digits = test_images[0:10]
>>> predictions = model.predict(test_digits)
>>> predictions[0]


array([1.6159515e-08, 8.0507476e-11, 5.6244926e-06, 4.3155812e-04,
       9.7005910e-12, 6.5438734e-08, 6.3723007e-14, 9.9955851e-01,
       5.0597453e-07, 3.6419328e-06], dtype=float32)

In [10]:
predictions[0].argmax() 

predictions[0][7] 


0.9995585

In [11]:
test_labels[0] 


7

In [12]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")


313/313 [==============================] - 1s 3ms/step - loss: 0.0649 - accuracy: 0.9811
test_acc: 0.9811000227928162
